# Generated by Django 3.2 on 2022-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(blank=True, default='None', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(default='None'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='None', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_list',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
